import test from 'node:test';
import assert from 'node:assert/strict';
import { DesktopController } from '../src/controller.js';
import { assertApp,normalizeAllowedApps,validateKeys } from '../src/policy.js';
import { FakeBackend } from './fake-backend.js';

const execution=(id='a')=>({agent:{id},signal:new AbortController().signal});
async function fixture(options={}) {const backend=new FakeBackend();const controller=new DesktopController(backend,options);const exec=execution();const {windows}=await controller.listWindows('a',exec.signal);const window=windows[0].id;const state=await controller.observe('a',{window,include_text:true},exec);return {backend,controller,exec,window,state};}
const input=f=>({window:f.window,observation_id:f.state.observation_id});

test('opaque binding survives changing title; text is verified without retry',async()=>{const f=await fixture();f.backend.delayReads=2;const result=await f.controller.act('a','type_text',{...input(f),text:'hellowworl'},f.exec);assert.equal(result.status,'verified');assert.equal(result.verification.actual,'hellowworl');assert.equal(result.state.window.id,f.window);assert.equal(f.backend.calls.filter(c=>c.action==='type_text').length,1);});
test('replaced HWND owner cannot reconnect an old window id',async()=>{const f=await fixture();f.backend.window.processStartedAt='new-owner';await assert.rejects(f.controller.act('a','click',{...input(f),element_index:1},f.exec),/Window closed|owner/);assert.equal(f.backend.calls.filter(c=>c.action==='click').length,0);});
test('observation is consumed before action and rejected on reuse',async()=>{const f=await fixture();await f.controller.act('a','click',{...input(f),element_index:1},f.exec);await assert.rejects(f.controller.act('a','click',{...input(f),element_index:1},f.exec),/expired|consumed/);});
test('cross-agent observations and window ids are rejected',async()=>{const f=await fixture();await assert.rejects(f.controller.observe('b',{window:f.window},execution('b')),/Choose a window/);await assert.rejects(f.controller.act('b','click',{...input(f),element_index:1},execution('b')),/belongs to another/);});
test('expired observation rejects before any input',async()=>{let now=10;const f=await fixture({now:()=>now,ttlMs:10});now=25;await assert.rejects(f.controller.act('a','click',{...input(f),element_index:1},f.exec),/expired/);});
test('screenshot pixels are scaled and mapped into moved window once',async()=>{const f=await fixture();f.backend.window.boundingBox.x+=50;f.backend.window.boundingBox.y+=30;await f.controller.act('a','click',{...input(f),x:100,y:80},f.exec);const click=f.backend.calls.find(c=>c.action==='click');assert.equal(click.args.x,350);assert.equal(click.args.y,390);});
test('resizing invalidates coordinate actions',async()=>{const f=await fixture();f.backend.window.boundingBox.width+=20;await assert.rejects(f.controller.act('a','click',{...input(f),x:10,y:10},f.exec),/resized/);});
test('occluded or absent screenshot prohibits coordinates',async()=>{const f=await fixture();f.backend.occluded=true;const state=await f.controller.observe('a',{window:f.window,include_text:true},f.exec);assert.equal(state.screenshot,null);await assert.rejects(f.controller.act('a','click',{window:f.window,observation_id:state.observation_id,x:10,y:10},f.exec),/usable screenshot/);});
test('out-of-image coordinates reject before input',async()=>{const f=await fixture();await assert.rejects(f.controller.act('a','click',{...input(f),x:500,y:10},f.exec),/inside/);});
test('focus missing forbids typing; Document focus is accepted',async()=>{const f=await fixture();f.backend.focused=false;const state=await f.controller.observe('a',{window:f.window,include_text:true},f.exec);await assert.rejects(f.controller.act('a','type_text',{window:f.window,observation_id:state.observation_id,text:'x'},f.exec),/focused editable/);});
test('failed input reports unknown and does not automatically replay',async()=>{const f=await fixture();f.backend.failAction='type_text';const result=await f.controller.act('a','type_text',{...input(f),text:'x'},f.exec);assert.equal(result.status,'outcome_unknown');assert.match(result.next,/Reobserve/);assert.equal(f.backend.calls.filter(c=>c.action==='type_text').length,1);await assert.rejects(f.controller.act('a','type_text',{...input(f),text:'x'},f.exec),/consumed/);});
test('refresh failure does not report input as not executed',async()=>{const f=await fixture();const original=f.backend.request.bind(f.backend);f.backend.request=async(a,b,s)=>{const r=await original(a,b,s);if(a==='type_text')f.backend.failAction='snapshot';return r;};const result=await f.controller.act('a','type_text',{...input(f),text:'x'},f.exec);assert.equal(result.status,'outcome_unknown');assert.equal(f.backend.calls.filter(c=>c.action==='type_text').length,1);});
test('verification timeout retains actual partial value and never resends',async()=>{const f=await fixture({verifyMs:120});f.backend.delayReads=100;const result=await f.controller.act('a','type_text',{...input(f),text:'longer'},f.exec);assert.equal(result.status,'outcome_unknown');assert.equal(result.verification.actual,'');assert.equal(f.backend.calls.filter(c=>c.action==='type_text').length,1);});
test('set_value reads the exact observed element and permits intended replacement',async()=>{const f=await fixture();f.backend.value='existing';f.state=await f.controller.observe('a',{window:f.window,include_text:true},f.exec);const result=await f.controller.act('a','set_value',{...input(f),element_index:1,value:'replacement'},f.exec);assert.equal(result.status,'verified');assert.equal(result.verification.actual,'replacement');});
test('non-empty document insertion is dispatched, not falsely verified',async()=>{const f=await fixture();f.backend.value='existing';const state=await f.controller.observe('a',{window:f.window,include_text:true},f.exec);const result=await f.controller.act('a','type_text',{window:f.window,observation_id:state.observation_id,text:'+'},f.exec);assert.equal(result.status,'dispatched');});
test('concurrent agents share a strictly serialized desktop queue',async()=>{const f=await fixture();f.backend.latency=5;await Promise.all([f.controller.listWindows('a',f.exec.signal),f.controller.listWindows('b',f.exec.signal),f.controller.listApps('a',f.exec.signal)]);assert.equal(f.backend.maxInFlight,1);});
test('rejected approval sends no input and consequential actions request it',async()=>{let deny=false,consequential=false;const f=await fixture({authorize:async(a,e,c)=>{consequential=c;if(deny)throw new Error('rejected');}});deny=true;await assert.rejects(f.controller.act('a','click',{...input(f),element_index:1,requires_confirmation:true},f.exec),/rejected/);assert.equal(consequential,true);assert.equal(f.backend.calls.filter(c=>c.action==='click').length,0);});
test('stop invalidates queued work even when immediately resumed',async()=>{const f=await fixture();f.backend.latency=10;const running=f.controller.listWindows('a',f.exec.signal);await new Promise(r=>setTimeout(r,1));const queued=f.controller.observe('a',{window:f.window},f.exec);const rejected=assert.rejects(queued,/stopped/);f.controller.stop();f.controller.resume();await running;await rejected;await assert.rejects(f.controller.act('a','click',{...input(f),element_index:1},f.exec),/expired|consumed/);});
test('pre-cancelled call never starts a backend request',async()=>{const f=await fixture();const abort=new AbortController();abort.abort();const before=f.backend.calls.length;await assert.rejects(f.controller.act('a','click',{...input(f),element_index:1},{...f.exec,signal:abort.signal}));assert.equal(f.backend.calls.length,before);});
test('app catalog excludes browsers and refuses arbitrary launch arguments',async()=>{const f=await fixture();const result=await f.controller.listApps('a',f.exec.signal);assert.equal(result.apps.some(a=>a.id==='chrome.exe'),false);await assert.rejects(f.controller.launch('a','notepad.exe & calc.exe',f.exec),/exact|catalog|Select/);});
test('policy excludes browsers, terminal and credentials; key aliases work',()=>{for(const a of ['chrome.exe','msedge.exe','pwsh.exe','cmd.exe','1password.exe'])assert.throws(()=>assertApp(a),/DENIED/);assert.throws(()=>normalizeAllowedApps(['C:\\Windows\\notepad.exe']),/name/);assert.throws(()=>normalizeAllowedApps(['*.exe']),/DENIED/);assert.throws(()=>validateKeys('Win+R'),/KEY_DENIED/);assert.deepEqual(validateKeys('Control_L+Shift_L+a'),['Ctrl','Shift','a']);});
test('content changed after observation refuses input without replacement',async()=>{const f=await fixture();f.backend.value='human edit';const result=await f.controller.act('a','type_text',{...input(f),text:'x'},f.exec);assert.equal(result.status,'outcome_unknown');assert.match(result.error.message,/CONTENT_CHANGED/);assert.equal(f.backend.value,'human edit');});
