window.__ModuleLoader__.load({
  id: '@very12345/dsh-computer-use-windows',
  factory: require => {
    const R = require('react'), h = R.createElement, route = '/plugins/computer-use-windows';
    const css = `
      .cuw-page{--cu-text:var(--dsw-alias-label-primary,#20242c);--cu-muted:var(--dsw-alias-label-secondary,#69717f);--cu-border:var(--dsw-alias-border-l3,#e4e7ec);--cu-surface:var(--dsw-alias-bg-layer-2,#fff);--cu-soft:var(--dsw-alias-bg-layer-3,#f7f8fa);--cu-accent:#3d64df;color:var(--cu-text);max-width:720px;padding:12px 0 32px;font-size:14px;line-height:1.5}
      .cuw-page *{box-sizing:border-box}.cuw-page button,.cuw-page input{font:inherit}.cuw-page button{cursor:pointer}.cuw-page button:disabled{cursor:default;opacity:.45}.cuw-page button:focus-visible,.cuw-page input:focus-visible{outline:3px solid #8ba9ff;outline-offset:3px}
      .cuw-header{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:30px}.cuw-title-wrap{display:flex;align-items:center;gap:14px}.cuw-symbol{display:grid;place-items:center;flex:none;width:44px;height:44px;border:1px solid var(--cu-border);border-radius:13px;background:var(--cu-soft)}.cuw-page h2{margin:0;font-size:18px;line-height:1.5;font-weight:600;letter-spacing:normal}.cuw-subtitle{margin:5px 0 0;color:var(--cu-muted);font-size:13px}.cuw-status{display:inline-flex;align-items:center;gap:7px;padding:5px 10px;border-radius:20px;border:1px solid var(--cu-border);color:var(--cu-muted);font-size:12px;white-space:nowrap}.cuw-dot{width:6px;height:6px;border-radius:50%;background:#949ca8}.cuw-status[data-active=true] .cuw-dot{background:#21936a}.cuw-status[data-paused=true] .cuw-dot{background:#c58c2e}
      .cuw-section{margin-top:26px}.cuw-heading{display:flex;align-items:center;gap:8px;margin:0 0 10px;font-size:13px;font-weight:600;color:var(--cu-muted)}.cuw-panel{border:1px solid var(--cu-border);border-radius:12px;background:var(--cu-surface);overflow:hidden}.cuw-row{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:20px}.cuw-row+.cuw-row{border-top:1px solid var(--cu-border)}.cuw-label{font-weight:550;font-size:14px;margin:0}.cuw-help{color:var(--cu-muted);font-size:12px;margin:4px 0 0;line-height:1.65}.cuw-switch{display:block;position:relative;flex:none;width:40px;height:24px;border:0;border-radius:20px;background:#a0a7b2;padding:3px;transition:background .15s}.cuw-switch[aria-checked=true]{background:var(--cu-accent)}.cuw-switch-knob{display:block;width:18px;height:18px;border-radius:50%;background:#fff;box-shadow:0 1px 3px #0002;transform:translateX(0);transition:transform .15s}.cuw-switch[aria-checked=true] .cuw-switch-knob{transform:translateX(16px)}
      .cuw-access{padding:6px}.cuw-option{display:flex;align-items:center;gap:13px;width:100%;border:1px solid transparent;border-radius:8px;background:transparent;color:var(--cu-text);padding:14px;text-align:left;transition:none}.cuw-option:hover{background:var(--cu-soft)}.cuw-option[aria-checked=true]{background:var(--cu-soft);border-color:var(--cu-border)}.cuw-option-icon{display:grid;place-items:center;flex:none;color:var(--cu-muted);width:28px;height:28px}.cuw-option-copy{flex:1;min-width:0}.cuw-option-title{display:flex;align-items:center;gap:8px;font-weight:550}.cuw-recommended{font-weight:400;font-size:10px;color:var(--cu-text);background:#3d64df12;padding:1px 6px;border-radius:4px}.cuw-radio{width:16px;height:16px;flex:none;border:1.5px solid #9ca5b3;border-radius:50%;display:grid;place-items:center}.cuw-option[aria-checked=true] .cuw-radio{border-color:var(--cu-accent)}.cuw-option[aria-checked=true] .cuw-radio:after{content:'';width:8px;height:8px;border-radius:50%;background:var(--cu-accent)}
      .cuw-apps{padding:0 20px 20px;border-top:1px solid var(--cu-border)}.cuw-apps-head{display:flex;justify-content:space-between;align-items:center;margin:16px 0 10px;font-size:12px;color:var(--cu-muted)}.cuw-app-row{display:flex;align-items:center;gap:11px;padding:11px 0;border-bottom:1px solid var(--cu-border)}.cuw-app-icon{display:grid;place-items:center;width:32px;height:32px;background:var(--cu-soft);border:1px solid var(--cu-border);border-radius:8px;color:var(--cu-muted)}.cuw-app-name{flex:1;font-size:13px}.cuw-app-exe{font-size:11px;color:var(--cu-muted);margin-top:1px}.cuw-remove{border:0;background:transparent;color:var(--cu-muted);padding:6px;border-radius:6px;display:grid;place-items:center}.cuw-remove:hover{background:var(--cu-soft);color:var(--cu-text)}.cuw-add{display:flex;gap:8px;margin-top:14px}.cuw-input{flex:1;min-width:0;background:var(--cu-surface);color:var(--cu-text);height:36px;padding:0 11px;border:1px solid var(--cu-border);border-radius:7px;font-size:12px!important}.cuw-input::placeholder{color:var(--cu-muted);opacity:.8}.cuw-button{display:inline-flex;align-items:center;justify-content:center;gap:6px;background:var(--cu-surface);color:var(--cu-text);border:1px solid var(--cu-border);padding:7px 12px;border-radius:7px;font-size:12px!important;white-space:nowrap}.cuw-button:hover{background:var(--cu-soft)}.cuw-button-primary{background:var(--cu-accent);color:#fff;border-color:var(--cu-accent)}.cuw-button-primary:hover{background:#3156c8}.cuw-button-danger{color:var(--dsw-alias-label-error,#c73f38)}.cuw-empty{padding:16px 0 6px;color:var(--cu-muted);font-size:12px}.cuw-footnote{display:flex;align-items:flex-start;gap:8px;margin:12px 2px 0;font-size:12px;color:var(--cu-muted);line-height:1.65}.cuw-footnote svg{flex:none;margin-top:2px}.cuw-pause{padding:14px 20px;background:var(--cu-soft);display:flex;justify-content:space-between;align-items:center;gap:16px;border-top:1px solid var(--cu-border)}.cuw-footer{display:flex;align-items:center;gap:6px;margin-top:18px;color:var(--cu-muted);font-size:11px}.cuw-error{padding:12px 14px;border:1px solid var(--cu-border);border-radius:8px;color:var(--dsw-alias-label-error,#c73f38);background:var(--cu-soft);margin-top:14px;font-size:12px}.cuw-loading{height:180px;background:var(--cu-soft);border-radius:12px;display:grid;place-items:center;color:var(--cu-muted);font-size:13px}
      @media(max-width:520px){.cuw-header{align-items:flex-start;gap:10px}.cuw-page h2{font-size:18px}.cuw-row{padding:16px;gap:16px}.cuw-status{font-size:11px}.cuw-apps{padding:0 16px 16px}.cuw-symbol{width:38px;height:38px}.cuw-subtitle{max-width:210px}.cuw-add{flex-wrap:wrap}.cuw-input{min-width:160px}.cuw-pause{padding:14px 16px}}
      @media(prefers-reduced-motion:reduce){.cuw-page *{transition:none!important}}
    `;
    function icon(name,size=18){
      const paths={monitor:['M4 4h16v12H4z','M8 20h8','M12 16v4'],apps:['M3 3h7v7H3z','M14 3h7v7h-7z','M3 14h7v7H3z','M14 14h7v7h-7z'],shield:['M12 3 20 6v6c0 5-8 9-8 9s-8-4-8-9V6z','m8 12 3 3 5-6'],pause:['M8 5v14','M16 5v14'],plus:['M12 5v14','M5 12h14'],close:['m6 6 12 12','m18 6-12 12'],check:['m5 12 4 4 10-10']};
      return h('svg',{width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.65,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true},...(paths[name]||paths.monitor).map((d,i)=>h('path',{d,key:i})));
    }
    const names={'notepad.exe':'记事本','mspaint.exe':'画图','calc.exe':'计算器','explorer.exe':'文件资源管理器','winword.exe':'Microsoft Word','excel.exe':'Microsoft Excel','powerpnt.exe':'Microsoft PowerPoint','code.exe':'Visual Studio Code'};
    function apply(ctx){
      function Settings(){
        const [state,setState]=R.useState(null),[busy,setBusy]=R.useState(false),[error,setError]=R.useState(''),[draft,setDraft]=R.useState(''),[saved,setSaved]=R.useState(false);const requests=R.useRef(0);
        R.useEffect(()=>{let live=true;fetch(route).then(async r=>{const s=await r.json();if(!r.ok||!s.ok)throw new Error(s.error||'设置加载失败');return s;}).then(s=>{if(live)setState(s);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
        const change=async input=>{const request=++requests.current;setBusy(true);setError('');setSaved(false);try{const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const s=await r.json();if(!r.ok||!s.ok)throw new Error(s.error||'设置保存失败');if(request!==requests.current){const latest=requests.current;const fresh=await fetch(route).then(r=>r.json());if(latest===requests.current&&fresh.ok)setState(fresh);return false;}setState(s);setSaved(true);return true;}catch(e){if(request===requests.current)setError(e.message);return false;}finally{if(request===requests.current)setBusy(false);}};
        const supported=state?.supported===true,active=supported&&state.enabled&&!state.stopped,paused=supported&&state.enabled&&state.stopped,mode=state?.accessMode||'selected';
        const disabled=busy||!supported;
        const label=!state?'加载中':!supported?'需要 Windows':paused?'已暂停':active?'可用':'未开启';
        const add=async event=>{event.preventDefault();const app=draft.trim().toLowerCase();if(!app.endsWith('.exe')||/[<>:"/\\|?*]/.test(app)){setError('请输入应用的 .exe 名称，例如 WINWORD.EXE。');return;}if(state.allowedApps.includes(app)){setError('该应用已在列表中。');return;}if(await change({allowedApps:[...state.allowedApps,app]}))setDraft('');};
        const option=(id,title,detail,graphic,recommended)=>h('button',{type:'button',className:'cuw-option',role:'radio','aria-checked':mode===id,disabled,onClick:()=>change({accessMode:id})},h('span',{className:'cuw-option-icon'},icon(graphic,20)),h('span',{className:'cuw-option-copy'},h('span',{className:'cuw-option-title'},title,recommended?h('span',{className:'cuw-recommended'},'推荐'):null),h('span',{className:'cuw-help',style:{display:'block'}},detail)),h('span',{className:'cuw-radio'}));
        return h('section',{className:'cuw-page','aria-busy':busy},h('style',null,css),
          h('header',{className:'cuw-header'},h('div',{className:'cuw-title-wrap'},h('span',{className:'cuw-symbol'},icon('monitor',23)),h('div',null,h('h2',null,'电脑操作'),h('p',{className:'cuw-subtitle'},'让助手使用你的 Windows 桌面应用。'))),h('span',{className:'cuw-status','data-active':active,'data-paused':paused},h('span',{className:'cuw-dot'}),label)),
          !state?h('div',{className:'cuw-loading'},error?'暂时无法加载设置':'正在加载设置…'):h(R.Fragment,null,
            h('div',{className:'cuw-panel'},h('div',{className:'cuw-row'},h('div',null,h('p',{className:'cuw-label'},'启用桌面操作'),h('p',{className:'cuw-help'},'允许助手查看界面并操作鼠标、键盘。')),h('button',{type:'button',className:'cuw-switch',role:'switch','aria-label':'启用桌面操作','aria-checked':state.enabled,disabled,onClick:()=>change({enabled:!state.enabled})},h('span',{className:'cuw-switch-knob'}))),
              h('div',{className:'cuw-row'},h('div',null,h('p',{className:'cuw-label'},'显示操作提示'),h('p',{className:'cuw-help'},'半透明波浪、鲸鱼提示和鼠标位置指示。')),h('button',{type:'button',className:'cuw-switch',role:'switch','aria-label':'显示操作提示','aria-checked':state.showOverlay!==false,disabled,onClick:()=>change({showOverlay:state.showOverlay===false})},h('span',{className:'cuw-switch-knob'}))),paused?h('div',{className:'cuw-pause'},h('div',null,h('div',{className:'cuw-label'},'操作已暂停'),h('p',{className:'cuw-help'},'恢复后，助手会重新确认窗口状态。')),h('button',{type:'button',className:'cuw-button cuw-button-primary',disabled,onClick:()=>change({enabled:true})},'恢复操作')):null),
            h('div',{className:'cuw-section'},h('h3',{className:'cuw-heading'},icon('apps',16),'应用访问'),h('div',{className:'cuw-panel'},h('div',{className:'cuw-access',role:'radiogroup','aria-label':'应用访问范围'},option('desktop','所有普通应用','无需逐个授权，使用当前桌面上的应用。','monitor',true),option('selected','仅预先授权的应用','未添加的应用需要先获得你的确认。','apps',false)),mode==='selected'?h('div',{className:'cuw-apps'},h('div',{className:'cuw-apps-head'},h('span',null,'已授权应用'),h('span',null,state.allowedApps.length+' 个')),...state.allowedApps.map(app=>h('div',{className:'cuw-app-row',key:app},h('span',{className:'cuw-app-icon'},icon('monitor',16)),h('div',{className:'cuw-app-name'},names[app]||app,h('div',{className:'cuw-app-exe'},app)),h('button',{type:'button',className:'cuw-remove','aria-label':'移除 '+app,disabled,onClick:()=>change({allowedApps:state.allowedApps.filter(a=>a!==app)})},icon('close',14)))),!state.allowedApps.length?h('div',{className:'cuw-empty'},'还没有添加应用。你也可以选择上方的“所有普通应用”。'):null,h('form',{className:'cuw-add',onSubmit:add},h('input',{className:'cuw-input','aria-label':'应用可执行文件名称',value:draft,onChange:e=>setDraft(e.target.value),placeholder:'应用名称，例如 WINWORD.EXE',disabled,autoComplete:'off',spellCheck:false}),h('button',{type:'submit',className:'cuw-button',disabled:disabled||!draft.trim()},icon('plus',14),'添加应用'))):null),h('div',{className:'cuw-footnote'},icon('shield',15),h('span',null,'删除、发送和支付等操作仍需确认。浏览器、终端及敏感应用不在访问范围内。'))),
            h('div',{className:'cuw-section'},h('h3',{className:'cuw-heading'},icon('pause',16),'操作控制'),h('div',{className:'cuw-panel'},h('div',{className:'cuw-row'},h('div',null,h('p',{className:'cuw-label'},'停止当前操作'),h('p',{className:'cuw-help'},'立即中断鼠标和键盘操作，之后可手动恢复。')),h('button',{type:'button',className:'cuw-button cuw-button-danger',disabled:!supported||!active,onClick:()=>change({stop:true})},icon('pause',14),'立即停止'))),h('p',{className:'cuw-footnote'},'操作期间会使用前台窗口。请避免同时使用鼠标和键盘。')),
            h('div',{className:'cuw-footer',role:'status','aria-live':'polite'},saved&&!busy?icon('check',13):null,busy?'正在保存…':saved?'设置已保存':'设置自动保存')),
          error?h('div',{className:'cuw-error',role:'alert'},error,!state?h('button',{type:'button',className:'cuw-button',style:{marginLeft:12},onClick:()=>{setError('');fetch(route).then(r=>r.json()).then(setState).catch(e=>setError(e.message));}},'重试'):null):null);
      }
      ctx.slots.inject('settings.section',()=>ctx.slots.register({name:'settings.section',id:'computer-use-windows',label:'电脑操作',order:47},Settings));
    }
    return {name:'computer-use-windows-client',inject:['slots'],apply};
  }
});
